modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 2 (GPLv2)"

[[mods]]
modId="communism_lifeandart"
version="1.1.7"
displayName="Communism:Life And Art"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Tapio, MCreator"

[[dependencies.communism_lifeandart]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




